version: "2"
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - cyclop
    - asciicheck

formatters:
  enable:
    - golines
    - gofmt
    - goimports
  settings:
    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 120
      # Length of a tabulation.
      # Default: 4
      tab-len: 4
      # Shorten single-line comments.
      # Default: false
      shorten-comments: false
      # Default: true
      reformat-tags: true
      # Split chained methods on the dots as opposed to the arguments.
      # Default: true
      chain-split-dots: true
